name: haivantravel-frontend-user
services: 
  haivantravel-frontend-user:
    container_name: haivantravel-frontend-user
    image: haivantravel-frontend-user
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports: 
      - "2032:2032"
    env_file:
      - .env.production
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    networks: 
      - haivantravel_network
    
networks:
  haivantravel_network:
    external: true